### ISSUE TITLE
Assiette de Wasabi

### ISSUE THREAD

**Issue by Edel999** [EagleOfFire/ROS-cuisine-1.20.1#8]
La texture n'était la que pour faciliter le copy / paste, pour faire plusieur assiettes avec du wasabi. Mais il ne doit pas y avoir "d'assiette wasabi"
![image](https://github.com/user-attachments/assets/0208dbd1-12d2-4884-b7d2-90ad822f4a9b)

**Comment by EagleOfFire** [comment]
Je me disait aussi c'est bizarre.
Corrigé dans version 2.0
